### PR TITLE
Narrow down CDM compatibility range when new criteria requiring more specific CDM added (instead of failing)

### PR DESCRIPTION
**Pull request by pavgra**
Related to https://github.com/OHDSI/WebAPI/issues/1263

### CODE REVIEW

**Comment by chrisknoll** [comment]
I continue to have issues with how the cohort expression's compatabilty range is being reset during serialization (I believe determineCdmCompatability() is being invoked during serialize/deserialize).

I do not think we should be overwriting the CdmVersionRange property during seriaization.  Between versions of standardized analysis api, we could get one range or another based on the different versions of Standardized analysis API.  Instead, I think we should keep determineCdmCompatability(), but instead of blindly overwriting the expression's cdmVersionRange, we should use that information to prevent generation or provide warning messages.

So, my request with this PR is a more general issue: to remove updating CdmVersionRange in 'determineCdmCompatability()'.

**Comment by pavgra** [comment]
@chrisknoll , I thought that we agreed to fix the thing first in patch release of Atlas (not to delay the 2.7.3) and then, in 2.8.0, do the functional changes. Wasn’t that the plan?

**Comment by chrisknoll** [comment]
I'm not sure exactly what the plan was (I can't find it in my notes) but what i'm proposing (remove the cdm range assignment during serialziation) isn't a comprehensive solution to what needs to be done in 2.8, so I think we're both talking about making a quick/patch release prior to a more full fledged solution.

Patch (2.7.3) = remove cdmRange assignment during serialization
Functional Change (2.8)= Apply cdmRange assigment as part of the UI, use 'determineCdmRange' to detemrine errors/a default value the user can request, etc etc.

That's what I was thinking.  My instinct that just removing the check `!overallIntersection.equals(compatibilitySpec.getCdmVersionRange())` is not enough to prevent the issue from happening: won't we still get a 'failure to save' error if we have conflicting Place Of Service Location criteria?  Ie: will we still run into problems if someone saved an existing cohort definition with one cdmVersionRange and then re-opens it, adds POS Location criteria, and then tries to save..won't that save fail?

**Comment by pavgra** [comment]
> My instinct
> won't that save fail?

The PR resolves the issue which I linked it to. Could you please provide the other failing test case?

**Comment by chrisknoll** [comment]
> The PR resolves the issue which I linked it to. Could you please provide the other failing test case?

Not without changing one of the criteria specs to be <=6.0.  Here's what I did:

I went to look for some `@CdmVersion` range set to something <= 6.0 so I could specify a conflicting expression and see if I could trigger a failure to save.  Everything in the `@CdmVersion` annotaions calls for either >= 5.0, >=5.3 or >=6.0 so I coudln't get into a case where there was a conflict.  But, I looked at what the `Death` criteria was specified (since I believe the Death criteria may change between 5.x and 6.x...or, even if it isn't let's pretned that soemthing becomes obsolete in 6.0).

In this case, I entered a criteria that had death criteria (restricted to <= 6.0) with the POS Location criteria (>=6.1) and i was unable to save.  Even after removing the POS Location, however, the cdm range was fixed at >=6.1 so I was still unable to save.  So, I acknowledge and agree with the current `@CdmVersion` specifications we've applied to our criteria, there is still soemthign wrong with what we are doing.  To your point, that's something we can address in a 2.8 timeframe, and I do not believe that the issue you raised is not fixed with the PR you submitted.  

I can apply approval to the PR, I just don't want the approval of the PR to be misconstrued with an overall approval of what is happening with respect to CdmVersion checking during serialization.

**Comment by pavgra** [comment]
So, I don not see a contradiction between our points of view. The issue which I faced is resolved by the PR. Same as the current PR makes all current cases working. That’s what we want for 2.7.3. As of moving forward, again, I am all for discussing better ways of version handling (e.g. adding one more check into cohort definitions check mechanisms) and applying them. But that’s for 2.8 / 3.0. So, if you could put your approval on this 2.7.3 PR, would be great

**Pull request merged**
