### PR TITLE
Added support for minSegmentLength pathway analysis parameter.

### PR DESCRIPTION
**Pull request by chrisknoll**
This PR will provide a paramater for PathwayAnalysis designs to specify a minSegmentLength, described in OHDSI/WebAPI#808

Added initial test assets.

### CODE REVIEW

**Comment by chrisknoll** [comment]
@pavgra , this PR will remove the extra dependency to java-semver.

**Comment by pavgra** [comment]
@chrisknoll , there are conflicts in PR. Could you resolve?

**Comment by anthonysena** [comment]
Linking to OHDSI/WebAPI#779

**Comment by chrisknoll** [comment]
This should be resolved now. Ignore the dummy diff in the root pom.xml, I couldn't remove it.

**Review by anthonysena — APPROVED** [review]

**Pull request merged**
